apiVersion: v1
kind: Service
metadata:
  name: udacity-frontend
  labels:
    app: udacity-frontend
spec:
  ports:
    - name: '8100'
      port: 8100
      targetPort: 80
      protocol: TCP
  selector:
    app: udacity-frontend
