apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-frontend
  labels:
    app: udacity-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-frontend
  template:
    metadata:
      labels:
        app: udacity-frontend
    spec:
      containers:
        - image: demola07/udagram-frontend:v6
          name: udacity-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '250m'
            limits:
              cpu: '500m'
      restartPolicy: Always
